// Mock contentlayer2/generated for preview environment
// In a real environment, this would be generated by contentlayer

export interface Announcement {
  _id: string
  _raw: {
    sourceFilePath: string
    sourceFileName: string
    sourceFileDir: string
    contentType: string
    flattenedPath: string
  }
  type: "Announcement"
  title: string
  publishedAt: string
  summary: string
  tags: string[]
  priority: number
  expiresAt?: string
  attachments?: Array<{
    name: string
    url: string
  }>
  url: string
  slug: string
  isExpired: boolean
  body: {
    raw: string
    code: string
  }
}

export interface Post {
  _id: string
  _raw: {
    sourceFilePath: string
    sourceFileName: string
    sourceFileDir: string
    contentType: string
    flattenedPath: string
  }
  type: "Post"
  title: string
  publishedAt: string
  updatedAt?: string
  excerpt: string
  tags: string[]
  authors: string[]
  coverImage?: string
  url: string
  slug: string
  body: {
    raw: string
    code: string
  }
}

export interface LearnResource {
  _id: string
  _raw: {
    sourceFilePath: string
    sourceFileName: string
    sourceFileDir: string
    contentType: string
    flattenedPath: string
  }
  type: "LearnResource"
  title: string
  updatedAt: string
  type: "文章" | "视频" | "项目" | "数据集" | "幻灯片"
  level: "入门" | "进阶" | "实战"
  track: string
  duration?: string
  prerequisites?: string[]
  externalUrl?: string
  url: string
  slug: string
  body: {
    raw: string
    code: string
  }
}

export interface Meeting {
  _id: string
  _raw: {
    sourceFilePath: string
    sourceFileName: string
    sourceFileDir: string
    contentType: string
    flattenedPath: string
  }
  type: "Meeting"
  title: string
  date: string
  time: string
  location: string
  type: "线上" | "线下" | "混合"
  status: "即将开始" | "进行中" | "已结束"
  summary: string
  tags: string[]
  speaker?: string
  capacity?: number
  registered?: number
  meetingUrl?: string
  materials?: Array<{
    name: string
    url: string
  }>
  url: string
  slug: string
  body: {
    raw: string
    code: string
  }
}

// Mock data for preview - expanded with more realistic content
export const allAnnouncements: Announcement[] = [
  {
    _id: "announcement-1",
    _raw: {
      sourceFilePath: "content/announcements/2025-09-28-fall-recruiting.mdx",
      sourceFileName: "2025-09-28-fall-recruiting.mdx",
      sourceFileDir: "announcements",
      contentType: "mdx",
      flattenedPath: "announcements/2025-09-28-fall-recruiting",
    },
    type: "Announcement",
    title: "2025年秋季招新开始啦！",
    publishedAt: "2025-09-28",
    summary:
      "SBC生物信息学俱乐部2025年秋季招新正式开始，欢迎对生物信息学感兴趣的同学加入我们！我们将提供系统的培训和实践机会。",
    tags: ["招新", "活动"],
    priority: 1,
    expiresAt: "2025-10-15",
    url: "/announcements/2025-09-28-fall-recruiting",
    slug: "2025-09-28-fall-recruiting",
    isExpired: false,
    body: {
      raw: "# 2025年秋季招新\n\n欢迎加入SBC！",
      code: "preview-content",
    },
  },
  {
    _id: "announcement-2",
    _raw: {
      sourceFilePath: "content/announcements/workshop-announcement.mdx",
      sourceFileName: "workshop-announcement.mdx",
      sourceFileDir: "announcements",
      contentType: "mdx",
      flattenedPath: "announcements/workshop-announcement",
    },
    type: "Announcement",
    title: "Python生物信息学入门工作坊",
    publishedAt: "2025-09-20",
    summary: "面向零基础同学的Python生物信息学入门工作坊，将于10月5日举办，涵盖基础语法到实际应用。",
    tags: ["讲座", "活动"],
    priority: 0,
    expiresAt: "2025-10-05",
    url: "/announcements/workshop-announcement",
    slug: "workshop-announcement",
    isExpired: false,
    body: {
      raw: "# Python工作坊\n\n详细内容...",
      code: "preview-content",
    },
  },
  {
    _id: "announcement-3",
    _raw: {
      sourceFilePath: "content/announcements/competition-notice.mdx",
      sourceFileName: "competition-notice.mdx",
      sourceFileDir: "announcements",
      contentType: "mdx",
      flattenedPath: "announcements/competition-notice",
    },
    type: "Announcement",
    title: "全国大学生生物信息学竞赛报名通知",
    publishedAt: "2025-09-15",
    summary: "2025年全国大学生生物信息学竞赛开始报名，我们将组织团队参赛，欢迎有兴趣的同学报名。",
    tags: ["比赛", "通知"],
    priority: 0,
    expiresAt: "2025-09-30",
    url: "/announcements/competition-notice",
    slug: "competition-notice",
    isExpired: true,
    body: {
      raw: "# 竞赛通知\n\n报名详情...",
      code: "preview-content",
    },
  },
]

export const allPosts: Post[] = [
  {
    _id: "post-1",
    _raw: {
      sourceFilePath: "content/posts/2025-09-10-scanpy-qc-clustering.mdx",
      sourceFileName: "2025-09-10-scanpy-qc-clustering.mdx",
      sourceFileDir: "posts",
      contentType: "mdx",
      flattenedPath: "posts/2025-09-10-scanpy-qc-clustering",
    },
    type: "Post",
    title: "Scanpy单细胞数据质控与聚类分析教程",
    publishedAt: "2025-09-10",
    updatedAt: "2025-09-15",
    excerpt: "详细介绍如何使用Scanpy进行单细胞RNA测序数据的质量控制和聚类分析，包括数据预处理、降维、聚类等关键步骤。",
    tags: ["单细胞", "Python", "Scanpy", "教程"],
    authors: ["张三", "李四"],
    coverImage: "/placeholder.jpg",
    url: "/posts/2025-09-10-scanpy-qc-clustering",
    slug: "2025-09-10-scanpy-qc-clustering",
    body: {
      raw: "# Scanpy教程\n\n这是一个详细的教程...",
      code: "preview-content",
    },
  },
  {
    _id: "post-2",
    _raw: {
      sourceFilePath: "content/posts/r-ggplot2-visualization.mdx",
      sourceFileName: "r-ggplot2-visualization.mdx",
      sourceFileDir: "posts",
      contentType: "mdx",
      flattenedPath: "posts/r-ggplot2-visualization",
    },
    type: "Post",
    title: "R语言ggplot2数据可视化进阶技巧",
    publishedAt: "2025-09-05",
    excerpt: "深入探讨ggplot2的高级功能，包括自定义主题、复杂图形组合、交互式可视化等内容。",
    tags: ["R语言", "ggplot2", "数据可视化", "进阶"],
    authors: ["王五"],
    coverImage: "/placeholder.jpg",
    url: "/posts/r-ggplot2-visualization",
    slug: "r-ggplot2-visualization",
    body: {
      raw: "# ggplot2进阶\n\n可视化技巧...",
      code: "preview-content",
    },
  },
  {
    _id: "post-3",
    _raw: {
      sourceFilePath: "content/posts/genomics-pipeline-nextflow.mdx",
      sourceFileName: "genomics-pipeline-nextflow.mdx",
      sourceFileDir: "posts",
      contentType: "mdx",
      flattenedPath: "posts/genomics-pipeline-nextflow",
    },
    type: "Post",
    title: "使用Nextflow构建基因组学分析流水线",
    publishedAt: "2025-08-28",
    excerpt: "介绍如何使用Nextflow构建可重现、可扩展的基因组学数据分析流水线，提高分析效率。",
    tags: ["Nextflow", "基因组学", "流水线", "自动化"],
    authors: ["赵六", "钱七"],
    url: "/posts/genomics-pipeline-nextflow",
    slug: "genomics-pipeline-nextflow",
    body: {
      raw: "# Nextflow流水线\n\n构建指南...",
      code: "preview-content",
    },
  },
]

export const allLearnResources: LearnResource[] = [
  {
    _id: "resource-1",
    _raw: {
      sourceFilePath: "content/learn/resources/intro-bioinfo-7days.mdx",
      sourceFileName: "intro-bioinfo-7days.mdx",
      sourceFileDir: "learn/resources",
      contentType: "mdx",
      flattenedPath: "learn/resources/intro-bioinfo-7days",
    },
    type: "LearnResource",
    title: "7天入门生物信息学",
    updatedAt: "2025-09-15",
    type: "文章",
    level: "入门",
    track: "生物信息学基础",
    duration: "7天",
    prerequisites: ["基础生物学", "Python基础"],
    url: "/learn/resources/intro-bioinfo-7days",
    slug: "intro-bioinfo-7days",
    body: {
      raw: "# 7天入门生物信息学\n\n这是一个入门教程...",
      code: "preview-content",
    },
  },
  {
    _id: "resource-2",
    _raw: {
      sourceFilePath: "content/learn/resources/python-for-bioinformatics.mdx",
      sourceFileName: "python-for-bioinformatics.mdx",
      sourceFileDir: "learn/resources",
      contentType: "mdx",
      flattenedPath: "learn/resources/python-for-bioinformatics",
    },
    type: "LearnResource",
    title: "Python生物信息学编程实战",
    updatedAt: "2025-09-10",
    type: "项目",
    level: "进阶",
    track: "编程技能",
    duration: "4周",
    prerequisites: ["Python基础", "生物学概念"],
    url: "/learn/resources/python-for-bioinformatics",
    slug: "python-for-bioinformatics",
    body: {
      raw: "# Python实战\n\n编程练习...",
      code: "preview-content",
    },
  },
  {
    _id: "resource-3",
    _raw: {
      sourceFilePath: "content/learn/resources/single-cell-analysis.mdx",
      sourceFileName: "single-cell-analysis.mdx",
      sourceFileDir: "learn/resources",
      contentType: "mdx",
      flattenedPath: "learn/resources/single-cell-analysis",
    },
    type: "LearnResource",
    title: "单细胞RNA测序数据分析",
    updatedAt: "2025-09-08",
    type: "视频",
    level: "实战",
    track: "单细胞分析",
    duration: "6周",
    prerequisites: ["R语言", "统计学基础", "分子生物学"],
    externalUrl: "https://example.com/single-cell-course",
    url: "/learn/resources/single-cell-analysis",
    slug: "single-cell-analysis",
    body: {
      raw: "# 单细胞分析\n\n视频教程...",
      code: "preview-content",
    },
  },
  {
    _id: "resource-4",
    _raw: {
      sourceFilePath: "content/learn/resources/genomics-datasets.mdx",
      sourceFileName: "genomics-datasets.mdx",
      sourceFileDir: "learn/resources",
      contentType: "mdx",
      flattenedPath: "learn/resources/genomics-datasets",
    },
    type: "LearnResource",
    title: "常用基因组学数据集汇总",
    updatedAt: "2025-09-05",
    type: "数据集",
    level: "入门",
    track: "数据资源",
    duration: "1天",
    prerequisites: [],
    url: "/learn/resources/genomics-datasets",
    slug: "genomics-datasets",
    body: {
      raw: "# 数据集汇总\n\n资源列表...",
      code: "preview-content",
    },
  },
]

export const allMeetings: Meeting[] = [
  {
    _id: "meeting-1",
    _raw: {
      sourceFilePath: "content/meetings/2025-10-05-python-workshop.mdx",
      sourceFileName: "2025-10-05-python-workshop.mdx",
      sourceFileDir: "meetings",
      contentType: "mdx",
      flattenedPath: "meetings/2025-10-05-python-workshop",
    },
    type: "Meeting",
    title: "Python生物信息学入门工作坊",
    date: "2025-10-05",
    time: "14:00-17:00",
    location: "生命科学楼A201",
    type: "线下",
    status: "即将开始",
    summary: "面向零基础同学的Python生物信息学入门工作坊，涵盖Python基础语法、Biopython库使用、序列分析等内容。",
    tags: ["工作坊", "Python", "入门"],
    speaker: "张教授",
    capacity: 30,
    registered: 18,
    materials: [
      { name: "课程资料.pdf", url: "/materials/python-workshop.pdf" },
      { name: "练习代码.zip", url: "/materials/python-exercises.zip" },
    ],
    url: "/meetings/2025-10-05-python-workshop",
    slug: "2025-10-05-python-workshop",
    body: {
      raw: "# Python工作坊\n\n详细内容...",
      code: "preview-content",
    },
  },
  {
    _id: "meeting-2",
    _raw: {
      sourceFilePath: "content/meetings/2025-10-12-journal-club.mdx",
      sourceFileName: "2025-10-12-journal-club.mdx",
      sourceFileDir: "meetings",
      contentType: "mdx",
      flattenedPath: "meetings/2025-10-12-journal-club",
    },
    type: "Meeting",
    title: "文献讨论会：单细胞多组学分析",
    date: "2025-10-12",
    time: "19:00-20:30",
    location: "腾讯会议",
    type: "线上",
    status: "即将开始",
    summary: "本期文献讨论会将分享最新的单细胞多组学分析方法和应用，包括scRNA-seq、scATAC-seq等技术的整合分析。",
    tags: ["文献讨论", "单细胞", "多组学"],
    speaker: "李博士",
    capacity: 50,
    registered: 32,
    meetingUrl: "https://meeting.tencent.com/dm/123456789",
    materials: [{ name: "讨论文献.pdf", url: "/materials/single-cell-paper.pdf" }],
    url: "/meetings/2025-10-12-journal-club",
    slug: "2025-10-12-journal-club",
    body: {
      raw: "# 文献讨论会\n\n讨论内容...",
      code: "preview-content",
    },
  },
  {
    _id: "meeting-3",
    _raw: {
      sourceFilePath: "content/meetings/2025-09-28-monthly-meeting.mdx",
      sourceFileName: "2025-09-28-monthly-meeting.mdx",
      sourceFileDir: "meetings",
      contentType: "mdx",
      flattenedPath: "meetings/2025-09-28-monthly-meeting",
    },
    type: "Meeting",
    title: "SBC九月月度总结会议",
    date: "2025-09-28",
    time: "15:00-16:30",
    location: "生命科学楼B301",
    type: "混合",
    status: "已结束",
    summary: "九月份俱乐部活动总结，包括新成员介绍、项目进展汇报、下月活动计划等内容。",
    tags: ["月度会议", "总结", "规划"],
    speaker: "俱乐部主席",
    capacity: 40,
    registered: 35,
    meetingUrl: "https://meeting.tencent.com/dm/987654321",
    materials: [
      { name: "会议纪要.pdf", url: "/materials/september-summary.pdf" },
      { name: "十月计划.pptx", url: "/materials/october-plan.pptx" },
    ],
    url: "/meetings/2025-09-28-monthly-meeting",
    slug: "2025-09-28-monthly-meeting",
    body: {
      raw: "# 月度总结会议\n\n会议内容...",
      code: "preview-content",
    },
  },
  {
    _id: "meeting-4",
    _raw: {
      sourceFilePath: "content/meetings/2025-10-20-guest-lecture.mdx",
      sourceFileName: "2025-10-20-guest-lecture.mdx",
      sourceFileDir: "meetings",
      contentType: "mdx",
      flattenedPath: "meetings/2025-10-20-guest-lecture",
    },
    type: "Meeting",
    title: "特邀讲座：AI在药物发现中的应用",
    date: "2025-10-20",
    time: "16:00-17:30",
    location: "学术报告厅",
    type: "线下",
    status: "即将开始",
    summary: "邀请业界专家分享人工智能在药物发现领域的最新进展和应用案例，探讨AI技术如何加速新药研发。",
    tags: ["特邀讲座", "AI", "药物发现"],
    speaker: "王研究员（某知名制药公司）",
    capacity: 100,
    registered: 67,
    materials: [{ name: "讲座大纲.pdf", url: "/materials/ai-drug-discovery-outline.pdf" }],
    url: "/meetings/2025-10-20-guest-lecture",
    slug: "2025-10-20-guest-lecture",
    body: {
      raw: "# AI药物发现讲座\n\n讲座内容...",
      code: "preview-content",
    },
  },
]
